@startuml
actor User

User -> main : lancer simulation
main -> Univers : initialiser()

loop t < t_end

    main -> Stromer : stromer(u, Fo)

    Stromer -> Univers : getParticles()
    Stromer -> Univers : updateCells()

    loop pour chaque particule
        Stromer -> Particle : updatePosition()
        Stromer -> Boundary : conditionLimites(p)
    end

    loop pour chaque particule
        Stromer -> Forces : computeForce(p)
    end

    loop pour chaque particule
        Stromer -> Particle : updateVitesse()
    end

    Stromer -> Stromer : Fo = F

end
@enduml